### ISSUE TITLE
Latest Image

### ISSUE THREAD

**Issue by gamblor999** [raspberryenvoie/piRa1n-OS#2]
Hi Team,  

Looks like you have updated checkra1n to 12.4,  is it possible to get a prebuilt image that includes this new version also, currently the latest is [2021-05-15 piRa1n-OS].

Thanks for any help.

**Comment by raspberryenvoie** [comment]
Hi, the latest image already includes checkra1n 12.4. It was implemented in piRa1n v5.8 and the latest piRa1n-OS image ships with piRa1n 5.9.2.
